/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as DesignAnalyzeRouteImport } from './routes/design.analyze'
import { Route as PermittingIndexRouteImport } from './routes/permitting.index'
import { Route as PermittingAnalyzeRouteImport } from './routes/permitting.analyze'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout.index'
import { Route as DashboardLayoutApprovalsRouteImport } from './routes/dashboard/_layout.approvals'
import { Route as DashboardLayoutChecklistRouteImport } from './routes/dashboard/_layout.checklist'
import { Route as DashboardLayoutCityRouteImport } from './routes/dashboard/_layout.city'
import { Route as DashboardLayoutConstraintsRouteImport } from './routes/dashboard/_layout.constraints'
import { Route as DashboardLayoutDesignRouteImport } from './routes/dashboard/_layout.design'
import { Route as DashboardLayoutDocumentsRouteImport } from './routes/dashboard/_layout.documents'
import { Route as DashboardLayoutFeesRouteImport } from './routes/dashboard/_layout.fees'
import { Route as DashboardLayoutNotificationsRouteImport } from './routes/dashboard/_layout.notifications'
import { Route as DashboardLayoutPermitsRouteImport } from './routes/dashboard/_layout.permits'
import { Route as DashboardLayoutPrepareRouteImport } from './routes/dashboard/_layout.prepare'
import { Route as DashboardLayoutReviewsRouteImport } from './routes/dashboard/_layout.reviews'
import { Route as DashboardLayoutRoadmapRouteImport } from './routes/dashboard/_layout.roadmap'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/dashboard/_layout.settings'
import { Route as DashboardLayoutTimelineRouteImport } from './routes/dashboard/_layout.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignAnalyzeRoute = DesignAnalyzeRouteImport.update({
  id: '/design/analyze',
  path: '/design/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const PermittingIndexRoute = PermittingIndexRouteImport.update({
  id: '/permitting/',
  path: '/permitting/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermittingAnalyzeRoute = PermittingAnalyzeRouteImport.update({
  id: '/permitting/analyze',
  path: '/permitting/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutApprovalsRoute =
  DashboardLayoutApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChecklistRoute =
  DashboardLayoutChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCityRoute = DashboardLayoutCityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutConstraintsRoute =
  DashboardLayoutConstraintsRouteImport.update({
    id: '/constraints',
    path: '/constraints',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDesignRoute = DashboardLayoutDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutDocumentsRoute =
  DashboardLayoutDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutFeesRoute = DashboardLayoutFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutNotificationsRoute =
  DashboardLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPermitsRoute = DashboardLayoutPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutPrepareRoute = DashboardLayoutPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutReviewsRoute = DashboardLayoutReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutRoadmapRoute = DashboardLayoutRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutSettingsRoute = DashboardLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutTimelineRoute = DashboardLayoutTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/design/analyze': typeof DesignAnalyzeRoute
  '/permitting/analyze': typeof PermittingAnalyzeRoute
  '/design/': typeof DesignIndexRoute
  '/permitting/': typeof PermittingIndexRoute
  '/dashboard/approvals': typeof DashboardLayoutApprovalsRoute
  '/dashboard/checklist': typeof DashboardLayoutChecklistRoute
  '/dashboard/city': typeof DashboardLayoutCityRoute
  '/dashboard/constraints': typeof DashboardLayoutConstraintsRoute
  '/dashboard/design': typeof DashboardLayoutDesignRoute
  '/dashboard/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/fees': typeof DashboardLayoutFeesRoute
  '/dashboard/notifications': typeof DashboardLayoutNotificationsRoute
  '/dashboard/permits': typeof DashboardLayoutPermitsRoute
  '/dashboard/prepare': typeof DashboardLayoutPrepareRoute
  '/dashboard/reviews': typeof DashboardLayoutReviewsRoute
  '/dashboard/roadmap': typeof DashboardLayoutRoadmapRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/timeline': typeof DashboardLayoutTimelineRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/design/analyze': typeof DesignAnalyzeRoute
  '/permitting/analyze': typeof PermittingAnalyzeRoute
  '/design': typeof DesignIndexRoute
  '/permitting': typeof PermittingIndexRoute
  '/dashboard/approvals': typeof DashboardLayoutApprovalsRoute
  '/dashboard/checklist': typeof DashboardLayoutChecklistRoute
  '/dashboard/city': typeof DashboardLayoutCityRoute
  '/dashboard/constraints': typeof DashboardLayoutConstraintsRoute
  '/dashboard/design': typeof DashboardLayoutDesignRoute
  '/dashboard/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/fees': typeof DashboardLayoutFeesRoute
  '/dashboard/notifications': typeof DashboardLayoutNotificationsRoute
  '/dashboard/permits': typeof DashboardLayoutPermitsRoute
  '/dashboard/prepare': typeof DashboardLayoutPrepareRoute
  '/dashboard/reviews': typeof DashboardLayoutReviewsRoute
  '/dashboard/roadmap': typeof DashboardLayoutRoadmapRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/timeline': typeof DashboardLayoutTimelineRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/design/analyze': typeof DesignAnalyzeRoute
  '/permitting/analyze': typeof PermittingAnalyzeRoute
  '/design/': typeof DesignIndexRoute
  '/permitting/': typeof PermittingIndexRoute
  '/dashboard/_layout/approvals': typeof DashboardLayoutApprovalsRoute
  '/dashboard/_layout/checklist': typeof DashboardLayoutChecklistRoute
  '/dashboard/_layout/city': typeof DashboardLayoutCityRoute
  '/dashboard/_layout/constraints': typeof DashboardLayoutConstraintsRoute
  '/dashboard/_layout/design': typeof DashboardLayoutDesignRoute
  '/dashboard/_layout/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/_layout/fees': typeof DashboardLayoutFeesRoute
  '/dashboard/_layout/notifications': typeof DashboardLayoutNotificationsRoute
  '/dashboard/_layout/permits': typeof DashboardLayoutPermitsRoute
  '/dashboard/_layout/prepare': typeof DashboardLayoutPrepareRoute
  '/dashboard/_layout/reviews': typeof DashboardLayoutReviewsRoute
  '/dashboard/_layout/roadmap': typeof DashboardLayoutRoadmapRoute
  '/dashboard/_layout/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/_layout/timeline': typeof DashboardLayoutTimelineRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/construction'
    | '/contact'
    | '/finance'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/dashboard'
    | '/design/analyze'
    | '/permitting/analyze'
    | '/design/'
    | '/permitting/'
    | '/dashboard/approvals'
    | '/dashboard/checklist'
    | '/dashboard/city'
    | '/dashboard/constraints'
    | '/dashboard/design'
    | '/dashboard/documents'
    | '/dashboard/fees'
    | '/dashboard/notifications'
    | '/dashboard/permits'
    | '/dashboard/prepare'
    | '/dashboard/reviews'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/timeline'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/construction'
    | '/contact'
    | '/finance'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/design/analyze'
    | '/permitting/analyze'
    | '/design'
    | '/permitting'
    | '/dashboard/approvals'
    | '/dashboard/checklist'
    | '/dashboard/city'
    | '/dashboard/constraints'
    | '/dashboard/design'
    | '/dashboard/documents'
    | '/dashboard/fees'
    | '/dashboard/notifications'
    | '/dashboard/permits'
    | '/dashboard/prepare'
    | '/dashboard/reviews'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/timeline'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/construction'
    | '/contact'
    | '/finance'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/_layout'
    | '/design/analyze'
    | '/permitting/analyze'
    | '/design/'
    | '/permitting/'
    | '/dashboard/_layout/approvals'
    | '/dashboard/_layout/checklist'
    | '/dashboard/_layout/city'
    | '/dashboard/_layout/constraints'
    | '/dashboard/_layout/design'
    | '/dashboard/_layout/documents'
    | '/dashboard/_layout/fees'
    | '/dashboard/_layout/notifications'
    | '/dashboard/_layout/permits'
    | '/dashboard/_layout/prepare'
    | '/dashboard/_layout/reviews'
    | '/dashboard/_layout/roadmap'
    | '/dashboard/_layout/settings'
    | '/dashboard/_layout/timeline'
    | '/dashboard/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  FinanceRoute: typeof FinanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DesignAnalyzeRoute: typeof DesignAnalyzeRoute
  PermittingAnalyzeRoute: typeof PermittingAnalyzeRoute
  DesignIndexRoute: typeof DesignIndexRoute
  PermittingIndexRoute: typeof PermittingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analyze': {
      id: '/design/analyze'
      path: '/design/analyze'
      fullPath: '/design/analyze'
      preLoaderRoute: typeof DesignAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permitting/': {
      id: '/permitting/'
      path: '/permitting'
      fullPath: '/permitting/'
      preLoaderRoute: typeof PermittingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permitting/analyze': {
      id: '/permitting/analyze'
      path: '/permitting/analyze'
      fullPath: '/permitting/analyze'
      preLoaderRoute: typeof PermittingAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/approvals': {
      id: '/dashboard/_layout/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardLayoutApprovalsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/checklist': {
      id: '/dashboard/_layout/checklist'
      path: '/checklist'
      fullPath: '/dashboard/checklist'
      preLoaderRoute: typeof DashboardLayoutChecklistRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/city': {
      id: '/dashboard/_layout/city'
      path: '/city'
      fullPath: '/dashboard/city'
      preLoaderRoute: typeof DashboardLayoutCityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/constraints': {
      id: '/dashboard/_layout/constraints'
      path: '/constraints'
      fullPath: '/dashboard/constraints'
      preLoaderRoute: typeof DashboardLayoutConstraintsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/design': {
      id: '/dashboard/_layout/design'
      path: '/design'
      fullPath: '/dashboard/design'
      preLoaderRoute: typeof DashboardLayoutDesignRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/documents': {
      id: '/dashboard/_layout/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardLayoutDocumentsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/fees': {
      id: '/dashboard/_layout/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardLayoutFeesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/notifications': {
      id: '/dashboard/_layout/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardLayoutNotificationsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/permits': {
      id: '/dashboard/_layout/permits'
      path: '/permits'
      fullPath: '/dashboard/permits'
      preLoaderRoute: typeof DashboardLayoutPermitsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/prepare': {
      id: '/dashboard/_layout/prepare'
      path: '/prepare'
      fullPath: '/dashboard/prepare'
      preLoaderRoute: typeof DashboardLayoutPrepareRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/reviews': {
      id: '/dashboard/_layout/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardLayoutReviewsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/roadmap': {
      id: '/dashboard/_layout/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardLayoutRoadmapRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/timeline': {
      id: '/dashboard/_layout/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardLayoutTimelineRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutApprovalsRoute: typeof DashboardLayoutApprovalsRoute
  DashboardLayoutChecklistRoute: typeof DashboardLayoutChecklistRoute
  DashboardLayoutCityRoute: typeof DashboardLayoutCityRoute
  DashboardLayoutConstraintsRoute: typeof DashboardLayoutConstraintsRoute
  DashboardLayoutDesignRoute: typeof DashboardLayoutDesignRoute
  DashboardLayoutDocumentsRoute: typeof DashboardLayoutDocumentsRoute
  DashboardLayoutFeesRoute: typeof DashboardLayoutFeesRoute
  DashboardLayoutNotificationsRoute: typeof DashboardLayoutNotificationsRoute
  DashboardLayoutPermitsRoute: typeof DashboardLayoutPermitsRoute
  DashboardLayoutPrepareRoute: typeof DashboardLayoutPrepareRoute
  DashboardLayoutReviewsRoute: typeof DashboardLayoutReviewsRoute
  DashboardLayoutRoadmapRoute: typeof DashboardLayoutRoadmapRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRoute
  DashboardLayoutTimelineRoute: typeof DashboardLayoutTimelineRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutApprovalsRoute: DashboardLayoutApprovalsRoute,
  DashboardLayoutChecklistRoute: DashboardLayoutChecklistRoute,
  DashboardLayoutCityRoute: DashboardLayoutCityRoute,
  DashboardLayoutConstraintsRoute: DashboardLayoutConstraintsRoute,
  DashboardLayoutDesignRoute: DashboardLayoutDesignRoute,
  DashboardLayoutDocumentsRoute: DashboardLayoutDocumentsRoute,
  DashboardLayoutFeesRoute: DashboardLayoutFeesRoute,
  DashboardLayoutNotificationsRoute: DashboardLayoutNotificationsRoute,
  DashboardLayoutPermitsRoute: DashboardLayoutPermitsRoute,
  DashboardLayoutPrepareRoute: DashboardLayoutPrepareRoute,
  DashboardLayoutReviewsRoute: DashboardLayoutReviewsRoute,
  DashboardLayoutRoadmapRoute: DashboardLayoutRoadmapRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRoute,
  DashboardLayoutTimelineRoute: DashboardLayoutTimelineRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  FinanceRoute: FinanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DesignAnalyzeRoute: DesignAnalyzeRoute,
  PermittingAnalyzeRoute: PermittingAnalyzeRoute,
  DesignIndexRoute: DesignIndexRoute,
  PermittingIndexRoute: PermittingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
